name: Publish

on: 
  release:
    types: [published]    

env:
  DOTNET_VERSION: '6.0.x'
  AZURE_WEBAPP_NAME: 'Fayble'
  AZURE_WEBAPP_PACKAGE_PATH: 'publish'

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:    
    - uses: actions/checkout@v2
    - name: Set VERSION variable from tag
      run: | 
          VERSION=${{ github.event.release.tag_name }}
          echo "VERSION=${VERSION:1}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
    
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish src/Fayble/Fayble.csproj -c Release -o ${{env.AZURE_WEBAPP_PACKAGE_PATH}} -p:Version=${{env.VERSION}}
      
    - uses: azure/webapps-deploy@v2      
      name: Deploy
      if: "!github.event.release.prelease"
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.DEMO_PUBLISH_PROFILE }}
        package: '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}'